{% set name = "veros-extra-setups" %}
{% set version = "1.5.2" %}
{% set python_min = "3.10" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name | replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 4095cb4aae83f7a88f6b13e50e2f1a706490d7df713dce6c166efb0d0d0ee4c4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - veros ==1.5.2

test:
  imports:
    - veros_extra_setups
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://veros-extra-setups.readthedocs.io
  summary: Extra setups for Veros, the versatile ocean simulator.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ocefpaf
